baseURL = 'https://blisteryy.github.io/-/'
languageCode = 'en-us'
title = '兰州市居家养老实录'
hasCJKLanguage = true
summaryLength = 100
theme = 'ananke'
publishDir = "docs"
canonifyurls = true


defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true